services:
  evolution:
    image: atendai/evolution-api:v2.2.3
    container_name: lab_evolution_api
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - lab_evolution_instances:/lab_evolution/instances
    networks:
      - automations_net

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - automations_net

  redis:
    image: redis:alpine
    restart: always
    networks:
      - automations_net

volumes:
  lab_evolution_instances:
  pg_data:

networks:
  automations_net:
    external: true
